parser: '@typescript-eslint/parser'

plugins:
  - '@typescript-eslint'

extends:
  - chartjs
  - plugin:@typescript-eslint/recommended

rules:
  # Replace stock eslint rules with typescript-eslint equivalents for proper
  # TypeScript support.
  no-use-before-define: "off"
  '@typescript-eslint/no-use-before-define': "error"
  no-shadow: "off"
  '@typescript-eslint/no-shadow': "error"
